-- ------------------------------
-- Produkte
CREATE TABLE Produktkategorie (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL
);

CREATE TABLE Mehrwertsteuer (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	SteuerSatz REAL NOT NULL DEFAULT 19.0
);

CREATE TABLE Download (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	Bildpfad TEXT NOT NULL
);

CREATE TABLE Produkt (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	KategorieID INTEGER NOT NULL,
	Bezeichnung TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	MehrwertsteuerID INTEGER NOT NULL,
	Details TEXT DEFAULT NULL,
	Nettopreis REAL NOT NULL DEFAULT 0.0,
	DatenblattID INTEGER DEFAULT NULL,
	CONSTRAINT fk_Produkt1 FOREIGN KEY (KategorieID) REFERENCES Produktkategorie(ID),
	CONSTRAINT fk_Produkt2 FOREIGN KEY (MehrwertsteuerID) REFERENCES Mehrwertsteuer(ID),
	CONSTRAINT fk_Produkt3 FOREIGN KEY (DatenblattID) REFERENCES Download(ID)
);

CREATE TABLE Produktbild (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bildpfad TEXT NOT NULL,
	ProduktID INTEGER NOT NULL,
	CONSTRAINT fk_Produktbild1 FOREIGN KEY (ProduktID) REFERENCES Produkt(ID)
);

-- ------------------------------
-- Person, Adresse
CREATE TABLE Land (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Kennzeichnung TEXT NOT NULL,
	Bezeichnung TEXT NOT NULL	
);

CREATE TABLE Adresse (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Strasse TEXT NOT NULL,
	Hausnummer TEXT NOT NULL,
	Adresszusatz TEXT NOT NULL,
	PLZ TEXT NOT NULL,
	Ort TEXT NOT NULL,
	LandID INTEGER NOT NULL,
	CONSTRAINT fk_Adresse1 FOREIGN KEY (LandID) REFERENCES Land(ID)
);

CREATE TABLE Person (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Anrede INTEGER NOT NULL DEFAULT 0,
	Vorname TEXT NOT NULL,
	Nachname TEXT NOT NULL,
	AdresseID INTEGER NOT NULL,
	Telefonnummer TEXT NOT NULL,
	Email TEXT NOT NULL,
	Geburtstag TEXT DEFAULT NULL,
	CONSTRAINT fk_Person1 FOREIGN KEY (AdresseID) REFERENCES Adresse(ID)
);

-- ------------------------------
-- Firma
CREATE TABLE Branche (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL
);

CREATE TABLE Firma (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Inhaber TEXT DEFAULT NULL,
	Beschreibung TEXT NOT NULL,
	AdresseID INTEGER NOT NULL,
	AnsprechpartnerID INTEGER DEFAULT NULL,
	BrancheID INTEGER DEFAULT NULL,
	CONSTRAINT fk_Firma1 FOREIGN KEY (AdresseID) REFERENCES Adresse(ID),
	CONSTRAINT fk_Firma2 FOREIGN KEY (AnsprechpartnerID) REFERENCES Person(ID),
	CONSTRAINT fk_Firma3 FOREIGN KEY (BrancheID) REFERENCES Branche(ID)
);

-- ------------------------------
-- Termine
CREATE TABLE Termin (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	Zeitpunkt TEXT NOT NULL,
	Dauer INTEGER NOT NULL DEFAULT 60,
	DienstleisterID INTEGER DEFAULT NULL,
	CONSTRAINT fk_Termin1 FOREIGN KEY (DienstleisterID) REFERENCES Firma(ID)
);

-- ------------------------------
-- Bestellwesen
CREATE TABLE Zahlungsart (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL
);

CREATE TABLE Bestellung (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bestellzeitpunkt TEXT NOT NULL,
	BestellerID INTEGER DEFAULT NULL,
	ZahlungsartID INTEGER NOT NULL,
	CONSTRAINT fk_Bestellung1 FOREIGN KEY (BestellerID) REFERENCES Person(ID),
	CONSTRAINT fk_Bestellung2 FOREIGN KEY (ZahlungsartID) REFERENCES Zahlungsart(ID)
);

CREATE TABLE Bestellposition (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	BestellungID INTEGER NOT NULL,
	ProduktID INTEGER NOT NULL,
	Menge INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT fk_Bestellposition1 FOREIGN KEY (BestellungID) REFERENCES Bestellung(ID),
	CONSTRAINT fk_Bestellposition2 FOREIGN KEY (ProduktID) REFERENCES Produkt(ID)
);

-- ------------------------------
-- Rezepte und Speisen
CREATE TABLE Speisenart (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	Bildpfad TEXT DEFAULT NULL
);

CREATE TABLE Gericht (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	SpeisenartID INTEGER NOT NULL,
	Zubereitung TEXT NOT NULL,
	Bildpfad TEXT DEFAULT NULL,
	CONSTRAINT fk_Gericht1 FOREIGN KEY (SpeisenartID) REFERENCES Speisenart(ID)
); 

CREATE TABLE Zutat (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	Beschreibung TEXT NOT NULL
);

CREATE TABLE Einheit (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL
);

CREATE TABLE Zutatenliste (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	GerichtID INTEGER NOT NULL,
	ZutatID INTEGER NOT NULL,
	Menge REAL NOT NULL DEFAULT 1.0,
	EinheitID INTEGER NOT NULL,
	CONSTRAINT fk_Zutatenliste1 FOREIGN KEY (GerichtID) REFERENCES Gericht(ID),
	CONSTRAINT fk_Zutatenliste2 FOREIGN KEY (ZutatID) REFERENCES Zutat(ID),
	CONSTRAINT fk_Zutatenliste3 FOREIGN KEY (EinheitID) REFERENCES Einheit(ID)
);

CREATE TABLE Bewertung (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	GerichtID INTEGER NOT NULL,
	Punkte INTEGER NOT NULL DEFAULT 1,
	Zeitpunkt TEXT NOT NULL,
	Bemerkung TEXT DEFAULT NULL,
	Ersteller TEXT DEFAULT NULL,
	CONSTRAINT fk_Bewertung1 FOREIGN KEY (GerichtID) REFERENCES Gericht(ID)
);

-- ------------------------------
-- Forum
CREATE TABLE Benutzerrolle (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL
);

CREATE TABLE Forumsbenutzer (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Benutzername TEXT NOT NULL,
	Geschlecht INTEGER NOT NULL DEFAULT 0,
	Geburtstag TEXT NOT NULL,
	Beitritt TEXT NOT NULL,
	RolleID INTEGER NOT NULL,
	CONSTRAINT fk_Forumsbenutzer1 FOREIGN KEY (RolleID) REFERENCES Benutzerrolle(ID)
);

CREATE TABLE Forumsbereich (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Thema TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	AdministratorID INTEGER NOT NULL,
	CONSTRAINT fk_Forumsbereich1 FOREIGN KEY (AdministratorID) REFERENCES Forumsbenutzer(ID)
);

CREATE TABLE Forumseintrag (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Beitrag TEXT NOT NULL,
	ErstellerID INTEGER NOT NULL,
	Erstellzeitpunkt TEXT NOT NULL,
	BereichsID INTEGER DEFAULT NULL,
	VaterID INTEGER DEFAULT NULL,
	Entfernt INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT fk_Forumseintrag1 FOREIGN KEY (ErstellerID) REFERENCES Forumsbenutzer(ID),
	CONSTRAINT fk_Forumseintrag2 FOREIGN KEY (BereichsID) REFERENCES Forumsbereich(ID),
	CONSTRAINT fk_Forumseintrag3 FOREIGN KEY (VaterID) REFERENCES Forumseintrag(ID)
);

-- ------------------------------
-- Kinoreservierung
CREATE TABLE Kinosaal (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	Leinwand INTEGER NOT NULL DEFAULT 100,
	Tonsystem TEXT NOT NULL,
	Projektion TEXT NOT NULL,
	Projektionsart INTEGER NOT NULL DEFAULT 0,
	Sitzreihen INTEGER NOT NULL DEFAULT 20,
	SitzeProReihe INTEGER NOT NULL DEFAULT 25,
	Geschoss TEXT NOT NULL
);

CREATE TABLE Filmgenre (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL
);

CREATE TABLE Reservierer (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Vorname TEXT NOT NULL,
	Nachname TEXT NOT NULL,
	Email TEXT NOT NULL
);

CREATE TABLE Film (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	GenreID INTEGER NOT NULL,
	FSK INTEGER NOT NULL DEFAULT 12,
	Dauer INTEGER NOT NULL DEFAULT 90,
	Regie TEXT NOT NULL,
	Darsteller TEXT NOT NULL,
	Preis REAL NOT NULL DEFAULT 10.0,
	Coverpfad TEXT DEFAULT NULL,
	Videopfad TEXT DEFAULT NULL,
	IMDB TEXT DEFAULT NULL,
	CONSTRAINT fk_Film1 FOREIGN KEY (GenreID) REFERENCES Filmgenre(ID)
);

CREATE TABLE Vorstellung (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FilmID INTEGER NOT NULL,
	KinosaalID INTEGER NOT NULL,
	Zeitpunkt TEXT NOT NULL,
	CONSTRAINT fk_Vorstellung1 FOREIGN KEY (FilmID) REFERENCES Film(ID),
	CONSTRAINT fk_Vorstellung2 FOREIGN KEY (KinosaalID) REFERENCES Kinosaal(ID)
);

CREATE TABLE Reservierung (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Zeitpunkt NUMERIC NOT NULL,
	ReserviererID INTEGER NOT NULL,
	ZahlungsartID INTEGER NOT NULL,
	VorstellungID INTEGER NOT NULL,
	CONSTRAINT fk_Reservierung1 FOREIGN KEY (ReserviererID) REFERENCES Reservierer(ID),
	CONSTRAINT fk_Reservierung2 FOREIGN KEY (ZahlungsartID) REFERENCES Zahlungsart(ID),
	CONSTRAINT fk_Reservierung3 FOREIGN KEY (VorstellungID) REFERENCES Vorstellung(ID)
);

CREATE TABLE ReservierterSitz (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ReservierungID INTEGER NOT NULL,
	Reihe INTEGER NOT NULL DEFAULT 1,
	Sitzplatz INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT fk_ReservierterSitz1 FOREIGN KEY (ReservierungID) REFERENCES Reservierung(ID)
);

-- ------------------------------
-- Benutzer
CREATE TABLE Benutzer (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Benutzername TEXT NOT NULL,
	Passwort TEXT NOT NULL,
	BenutzerrolleID INTEGER NOT NULL,
	PersonID INTEGER DEFAULT NULL,
	CONSTRAINT fk_Benutzer1 FOREIGN KEY (BenutzerrolleID) REFERENCES Benutzerrolle(ID),
	CONSTRAINT fk_Benutzer2 FOREIGN KEY (PersonID) REFERENCES Person(ID)
);