-- ------------------------------
-- Mehrwertsteuer
INSERT INTO Mehrwertsteuer (Bezeichnung, SteuerSatz) VALUES ('Standard', 19.0);
INSERT INTO Mehrwertsteuer (Bezeichnung, SteuerSatz) VALUES ('Reduziert', 7.0);

-- ------------------------------
-- Land
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Afghanistan','AF');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Ägypten','EG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Albanien','AL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Albanien','AL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Algerien','DZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Andorra','AD');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Angola','AO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Anguilla','AI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Antarktis','AQ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Antigua','AG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Äquatorial Guinea','GQ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Argentinien','AR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Armenien','AM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Aruba','AW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Aserbaidjan','AZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Äthiopien','ET');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Australien','AU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bahamas','BS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bahrain','BH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bangladesch','BD');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Barbados','BB');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Belgien','BE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Belize','BZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Benin','BJ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bermuda','BM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bhutan','BT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bolivien','BO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bosnien-Herzegowina','BA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Botswana','BW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bouvet Inseln','BV');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Brazilien','BR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('British Indien','IO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Brunei Darussalam','BN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Bulgarien','BG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Burkina Faso','BF');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Burundi','BI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Cayman Inseln','KY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Central Afrikanische Republik','CF');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Chile','CL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('China','CN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Cook Inseln - Elfenbeinküste','CI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Costa Rica','CR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Dänemark','DK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Deutschland','DE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Djibouti','DJ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Dominikanische Republik','DO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Ekuador','EC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('El Salvador','SV');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Eritrea','ER');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Estland','EE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Falkland Inseln','FK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Faröer Inseln (zu Dänemark)','FO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Fiji Inseln','FJ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Finnland','FI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Frankreich','FR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Gabun','GA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Gambia','GM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Georgien','GE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Ghana','GH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Gibraltar','GI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Grenada','GD');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Griechenland','GR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Grönland','GL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Guadeloupe','GP');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Guam','GU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Guatemala','GT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Guinea','GN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Guinea Bissau','GW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Guyana','GF');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Guyana','GY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Haiti','HT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Heard & McDonald Inseln','HM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Honduras','HN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Hongkong','HK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Indien','IN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Indonesien','ID');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Irak','IQ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Iran','IR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Irland','IE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Island','IS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Israel','IL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Italien','IT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Jamaika','JM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Japan','JP');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Jordanien','JO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Jugoslawien','YU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kambodscha','KH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kamerun','CM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kanada','CA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kapverdische Inseln','CV');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kasachstan','KZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kenya','KE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kirgisische Republik','KG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kiribati','KI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kokos Inseln','CC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kolumbien','CO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Komoroen','KM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kongo','CG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kroatien','HR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kuba','CU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Kuwait','KW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Laos','LA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Latvia','LV');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Lesotho','LS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Lettland','LV');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Libanon','LB');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Liberia','LR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Libyen','LY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Liechtenstein','LI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Litauen','LT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Lithuania','LT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Luxemburg','LU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Macao','MO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Madagascar','MG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Malawi','MW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Malaysia','MY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Maldiven','MV');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mali','ML');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Malta','MT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Marokko','MA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Marshall Inseln','MH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Martinique','MQ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mauritanien','MR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mauritius','MU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mayotte','YT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mazedonien','MK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mexico','MX');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mikronesien','FM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Moldavien','MD');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Monaco','MC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mongolei','MN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Montserrat','MS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Mozambique','MZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Myanmar','MM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Namibia','NA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Nauru','NR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Nepal','NP');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Neu Kaledonien','NC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Neuseeland','NZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Nicaragua','NI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Niederlande','NL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Niederländische Antillen','AN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Niger','NE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Nigeria','NG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Niue','NU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Nord-Korea','KP');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Nördliche Marianen Inseln','MP');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Norfolk Inseln','NF');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Norwegen','NO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Oman','OM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Ost Timor','TP');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Österreich','AT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Pakistan','PK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Palau','PW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Panama','PA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Papua Neuguinea','PG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Paraguay','PY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Peru','PE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Philippinen','PH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Pitcairn','PN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Polen','PL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Polynesien','PF');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Portugal','PT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Puerto Rico','PR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Qatar','QA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Reunion','RE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Ruanda','RW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Rumänien','RO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Russische Förderation','RU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Samoa','AS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Samoa','WS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('San Marino','SM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Saudi Arabien','SA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Schweden','SE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Schweiz','CH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Senegal','SN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Serbien','RS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Seychellen','SC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Sierra Leone','SL');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Singapur','SG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Slowakei','SK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Slowenien','SI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Solomonen Inseln','SB');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Somalia','SO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Sowjetunion','SU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Spanien','ES');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Sri Lanka','LK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('St. Helena','SH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('St. Kitts Nevis Anguill','KN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('St. Lucia','LC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('St. Pierre & Miquelon','PM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('St. Tome and Principe','ST');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('St.Vincent & Grenadine','VC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Süd Afrika','ZA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Süd Georgia und Sandwich Inseln','GS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Sudan','SD');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Süd-Korea','KR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Surinam','SR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Svalbard & Jan Mayen','SJ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Swaziland','SZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Syrien','SY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tadjikistan','TJ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Taiwan','TW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tansania','TZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Thailand','TH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Togo','TG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tokelau','TK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tonga','TO');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Trinidad & Tobago','TT');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tschad','TD');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tschechische Republik','CZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tschechoslovakei','CS');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tunesien','TN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Türkei','TR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Turkmenistan','TM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Turks & Caicos Inseln','TC');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Tuvalu','TV');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Uganda','UG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Ukraine','UA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Ungarn','HU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('United Kingdom (England)','UK');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('United States (USA)','US');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Uruguay','UY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Uzbekistan','UZ');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Vanuatu','VU');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Vatikanstadt','VA');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Venezuela','VE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Vereinigte Arabische Emirate','AE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Vereintes Königreich','GB');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Vietnam','VN');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Virgin Islands (britisch)','VG');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Virgin Islands (US)','VI');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Wallis & Futuna Inseln','WF');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Weihnachts Inseln','CX');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Weißrussland','BY');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('West Sahara','EH');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Yemen','YE');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Zaire','ZR');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Zambia','ZM');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Zimbabwe','ZW');
INSERT INTO Land (Bezeichnung, Kennzeichnung) VALUES ('Zypern','CY');

-- ------------------------------
-- Branche
INSERT INTO Branche (Bezeichnung) VALUES ('Industrie');
INSERT INTO Branche (Bezeichnung) VALUES ('Landwirtscahft');
INSERT INTO Branche (Bezeichnung) VALUES ('Dienstleistung');
INSERT INTO Branche (Bezeichnung) VALUES ('Gesundheit');
INSERT INTO Branche (Bezeichnung) VALUES ('Bildung');

-- ------------------------------
-- Zahlungsart
INSERT INTO Zahlungsart (Bezeichnung) VALUES ('Kreditkarte');
INSERT INTO Zahlungsart (Bezeichnung) VALUES ('PayPal');
INSERT INTO Zahlungsart (Bezeichnung) VALUES ('Überweisung');
INSERT INTO Zahlungsart (Bezeichnung) VALUES ('Rechnung');

-- ------------------------------
-- Einheit
INSERT INTO Einheit (Bezeichnung) VALUES ('kg');
INSERT INTO Einheit (Bezeichnung) VALUES ('g');
INSERT INTO Einheit (Bezeichnung) VALUES ('EL');
INSERT INTO Einheit (Bezeichnung) VALUES ('TL');
INSERT INTO Einheit (Bezeichnung) VALUES ('Liter');
INSERT INTO Einheit (Bezeichnung) VALUES ('dl');
INSERT INTO Einheit (Bezeichnung) VALUES ('ml');

-- ------------------------------
-- Benutzerrolle
INSERT INTO Benutzerrolle (Bezeichnung) VALUES ('Administrator');
INSERT INTO Benutzerrolle (Bezeichnung) VALUES ('Moderator');
INSERT INTO Benutzerrolle (Bezeichnung) VALUES ('Benutzer');


-- ------------------------------
-- Kinosaal
INSERT INTO Kinosaal (Bezeichnung, Leinwand, Tonsystem, Projektion, Projektionsart, Sitzreihen, SitzeProReihe, Geschoss) VALUES ('Saal 1', 67, 'Dolby SRD', 'Digitale Projektion', 0, 10, 22, 'Erdgeschoss');
INSERT INTO Kinosaal (Bezeichnung, Leinwand, Tonsystem, Projektion, Projektionsart, Sitzreihen, SitzeProReihe, Geschoss) VALUES ('Saal 2', 74, 'Dolby SRD', 'Digitale Projektion', 0, 12, 25, 'Erdgeschoss');
INSERT INTO Kinosaal (Bezeichnung, Leinwand, Tonsystem, Projektion, Projektionsart, Sitzreihen, SitzeProReihe, Geschoss) VALUES ('Saal 3', 122, 'Dolby Digital 7.1', 'Digitale 3D Projektion', 1, 15, 25, '1. Stock');
INSERT INTO Kinosaal (Bezeichnung, Leinwand, Tonsystem, Projektion, Projektionsart, Sitzreihen, SitzeProReihe, Geschoss) VALUES ('Saal 4', 108, 'Dolby SRD / DTS', 'Digitale 3D Projektion', 1, 13, 23, '2. Stock');

-- ------------------------------
-- Filmgenre
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Action');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Drama');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Komödie');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Fantasy');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Horror');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Krieg');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Musik');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Thriller');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Science Fiction');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Sport');
INSERT INTO Filmgenre (Bezeichnung) VALUES ('Western');

