CREATE TABLE Forumsbenutzer (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Benutzername TEXT NOT NULL,
	Beitritt TEXT NOT NULL,
);

CREATE TABLE Forumseintrag (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Beitrag TEXT NOT NULL,
	ErstellerID INTEGER NOT NULL,
	Erstellzeitpunkt TEXT NOT NULL,
	BereichsID INTEGER DEFAULT NULL,
	VaterID INTEGER DEFAULT NULL,
	Entfernt INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT fk_Forumseintrag1 FOREIGN KEY (ErstellerID) REFERENCES Forumsbenutzer(ID),
);

CREATE TABLE Benutzer (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Benutzername TEXT NOT NULL,
	Passwort TEXT NOT NULL,
	BenutzerrolleID INTEGER NOT NULL,
	PersonID INTEGER DEFAULT NULL,
	CONSTRAINT fk_Benutzer1 FOREIGN KEY (BenutzerrolleID) REFERENCES Benutzerrolle(ID),
	CONSTRAINT fk_Benutzer2 FOREIGN KEY (PersonID) REFERENCES Person(ID)
);